### Correct stars route
GET http://localhost:3000/stars

### 404 error
GET http://localhost:3000/wrong

### Get one star
GET http://localhost:3000/stars/6918c6405e085860122937f5

### Add new star
POST http://localhost:3000/stars 
content-type: application/json

{
    "name": "any",
    "distance": "131",
    "radius": "2d2",
    "mass": "22",
    "spectralClass": "any"
}

### Update star
PUT http://localhost:3000/stars/691ce096146380f7ff47f619
content-type: application/json

{
    "name": "any",
    "distance": "d",
    "radius": "33",
    "mass": "22",
    "spectralClass": "any"
}

### Delete star
DELETE http://localhost:3000/stars/691ce096146380f7ff47f619