### Correct stars route
GET http://localhost:3000/stars

### 404 error
GET http://localhost:3000/wrong

### Get one star
GET http://localhost:3000/stars/691df1cce0420b49f8de814f

### invalid star ID
GET http://localhost:3000/stars/invalid

### Add new star
POST http://localhost:3000/stars 
content-type: application/json

{
    "name": "any",
    "distance": "131",
    "radius": "22",
    "mass": "22",
    "spectralClass": "any"
}

### Update star
PUT http://localhost:3000/stars/691df1cce0420b49f8de814f
content-type: application/json

{
    "name": "any",
    "distance": "d",
    "radius": "33",
    "mass": "22",
    "spectralClass": "any"
}

### Delete star
DELETE http://localhost:3000/stars/691df1cce0420b49f8de814f


### Planets

### Get all
GET http://localhost:3000/planets

### Get one
GET http://localhost:3000/planets/6918d8a51062c31f1bb7c05f

### invalid planet ID
GET http://localhost:3000/planets/invalid

### Add new planet
POST http://localhost:3000/planets 
content-type: application/json

{
    "name": "any",
    "starName": "any",
    "starDistance": "any",
    "mass": "any",
    "gravity": "any",
    "moons": "any",
    "day": "any",
    "year": "any"
}